#!/bin/sh

cd "$(dirname "$0")"

if test -f ./router_main_init.js
then
	./router_main_init.js
	exit 0
fi

erconfig="config.json"
if test "x$1" != "x"
then
	erconfig="$1.json"
fi

/usr/bin/env nodejs ./main_cli.js --config "${erconfig}"

