#!/bin/sh

cd "$(dirname "$0")"

if test -f ./router_main_init.js
then
	./router_main_init.js >${clog} 2>&1
	exit 0
fi

erconfig="config.json"
clog="er-output.log"
if test "x$1" != "x"
then
	erconfig="$1.json"
	name="${1##*/}"
	clog="er-output-${name}.log"
fi

/usr/bin/env nodejs ./main_cli.js --config "${erconfig}" >${clog} 2>&1

