services:
  osiota:
    build:
      context: ./
    restart: unless-stopped
    #privileged: true  # Required for GPIO access
    #network_mode: host  # Often required for proper network discovery
    volumes:
      - ./config:/config
      - osiota-data:/data
#      - /dev:/dev  # Required for USB device access
#      - /sys:/sys
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0  # Zigbee stick (adjust device name if needed)
#      - /dev/ttyUSB1:/dev/ttyUSB1  # RS-485 adapter (adjust device name if needed)
#      - /dev/gpiomem:/dev/gpiomem  # GPIO access
#      - /dev/mem:/dev/mem  # Additional GPIO access
    ports:
      - 8080:8080

volumes:
  osiota-data:
