#!/bin/bash

### BEGIN INIT INFO
# Provides:	     energy-router
# Required-Start:    $network $remote_fs $syslog ntp
# Required-Stop:     $network $remote_fs $syslog ntp
# Should-Start:      lighttpd apache2 ethercat
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start IfN data router
### END INIT INFO

# Author: Simon Walz <walz@ifn.ing.tu-bs.de>

BASE="$(dirname "$(dirname "$(readlink /etc/init.d/energy-router)")")/"
PID=/run/energy-router.pid
LOG=/run/energy-router.log

USR=`stat -c %U "${BASE}"`

SCRIPTNAME="${0##*/}"
SCRIPTNAME="${SCRIPTNAME##[KS][0-9][0-9]}"

ERCONFIG=""
if [ "${SCRIPTNAME##energy-router-}" != "$SCRIPTNAME" ] ; then
	ERCONFIG="-${SCRIPTNAME##energy-router-}"
	name="${SCRIPTNAME##*/}"
	PID=/run/energy-router-${name}.pid
	LOG=/run/energy-router-${name}.log

fi


COMMAND="${BASE}main ${ERCONFIG}"

status() {
	echo
	echo "==== Status"

	if [ -f $PID ]
		then
		echo
		pidc="$(cat $PID)"
		echo "Pid file: $pidc [$PID]"
		pgrp=$(echo $( ps -p${pidc} o pgrp=))
		echo "PGRP: ${pgrp}"
		echo
		ps -e -O pgrp | grep -v grep | grep $pgrp
	else
		echo
		echo "No Pid file"
	fi
}
 
start() {
	if [ -f $PID ]
	then
		echo
		echo "Already started. PID: [$( cat $PID )]"
		# restart:
		stop ; echo "Sleeping..."; sleep 1 ;
	fi

	echo "==== Start"
	cd "$BASE"
	touch $PID
	if nohup sudo -u $USR $COMMAND >/dev/null 2>&1 &
	then
		echo $! >$PID
		echo "Done."
		echo "$(date '+%Y-%m-%d %X'): START" >>$LOG
	else
		echo "Error... "
		/bin/rm $PID
	fi
}


stop() {
	echo "==== Stop"

	if [ -f $PID ]
	then
		pidc="$(cat $PID)"
		pgrp=$(echo $( ps -p${pidc} o pgrp=))
		if kill -- -${pgrp}
		then
			echo "Done."
			echo "$(date '+%Y-%m-%d %X'): STOP" >>$LOG
		fi
		while kill -0 -- -${pgrp} 2>/dev/null; do
			sleep 1
		done
		/bin/rm $PID
	else
		echo "No pid file. Already stopped?"
	fi
}

case "$1" in
	'start')
		start
		;;
	'stop')
		stop
		;;
	'restart')
		stop ; echo "Sleeping..."; sleep 1 ;
		start
		;;
	'status')
		status
		;;
	*)
		echo
		echo "Usage: $0 { start | stop | restart | status }"
		echo
		exit 1
		;;
esac

exit 0
